//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int idDetalleVenta { get; set; }
        public int Venta_idVenta { get; set; }
        public Nullable<int> cantidadProducto { get; set; }
        public Nullable<double> totalVentaProducto { get; set; }
        public int DetalleProducto_idDetalleProducto { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual DetalleProducto DetalleProducto { get; set; }
    }
}
